name: echo test
on:
  push:
    branches: ["main"]
    # paths: ".github/*"
  pull_request:
    branches: ["main"]
    # paths: ".github/*"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: Hello
      run: echo "hello"
  build-2:
    needs: build
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v4.2.2
    - name: Checkout
      uses: pwd
    - name: Checkout
      uses: ls -la
    - name: Hello
      run: echo "bye bye"
