name: echo test
on:
  push:
    branches: ["main"]
    # paths: ".github/*"
  pull_request:
    branches: ["main"]
    # paths: ".github/*"
  workflow_dispatch:
env:
  user: roldanx
  file1: secret.txt
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: greet
      run: echo "hello $user"
    - name: show-secret
      run: |
        echo "furbo: ${{ secrets.TOP_SECRET }}" > $file1
    - name: artifact
      uses: actions/upload-artifact@v4
      with:
        name: furbo-secret
        path: $file1
        retention-days: 1
  build-2:
    needs: build
    runs-on: ubuntu-latest
    steps: 
    - name: checkout
      uses: actions/checkout@v4.2.2
    - name: pwd
      run: pwd
    - name: ls
      run: ls -la
    - name: say bye
      run: echo "bye bye $user"
